### ISSUE TITLE
Issue adding players after the first round.

### ISSUE THREAD

**Issue by Farvann** [ThatRickGuy/PGSwiss#77]
Last weekend I wan a tournament, and had a player show up late after most the first round tables were done.  Easy enough - he gets a first round bye, and we keep playing.

I added him into the roster (that worked just fine).
When I asked it to re-pair, the program threw an error about not finding a match up, and only showed 3 players for pairings.

Went back to round one, flagged this player as a bye, moved forward, same issues.

Started a new tournament, and was able to repro the issue.
Started another new tournament with him added from the get, gave him a bye, and it would not let me move past round two.

I've not had time to repro again this week with more steps/better details.

**Comment by ThatRickGuy** [comment]
I've been unable to recreate this in 1.11. Not sure if I fixed it and forgot to update this ticket or what, but if you have a chance to give it another try, please do.

**Comment by Farvann** [comment]
I'm sorry - I've stopped using the program some time ago, and moved to a
manual sorting / alternate scoring system.

**Comment by ThatRickGuy** [comment]
No worries. It sat on the back burner for a good while. Have some time today so I'm poking at it. If you give it another spin, let me know if you come across any more issues.
