### ISSUE TITLE
Round Results pre-populated with data

### ISSUE THREAD

**Issue by DanWasmer** [ThatRickGuy/PGSwiss#83]
When entering round results for round 2 and later, the CP/APD fields are filed in with previous information

**Comment by ThatRickGuy** [comment]
Haven't been able to reproduce this. Can you verify that you were looking at a fresh round (not hitting back to a previously scored round)?

The only fields that should get auto filled are CP on a scenario win (winner gets 5) and CP/APD on a concession, which are calculated.

**Comment by DanWasmer** [comment]
I got the error by running the round by round data from 6 pack #1 into the
system.  To my knowledge, it was a new round, but I don't know if I still
have the files on my machine or not.

Thanks

Dan Wasmer

**Comment by ThatRickGuy** [comment]
Tracked it down, fixed it as part of the last release refactoring of the way round.players is handled.
