### ISSUE TITLE
Same table pairings occur much more often than they should

### ISSUE THREAD

**Issue by DanWasmer** [ThatRickGuy/PGSwiss#92]
At tournament yestersay there were multiple same table pairings. Amidst seemed like software was trying to keep people on same table

**Comment by ThatRickGuy** [comment]
Fixed in 1.5.1

It wasn't intentional, but it tries to find unused tables starting with the winners' bracket. Only it wasn't correctly storing the history of tables, so a player winning out (or losing out) was very likely to wind up on the same table over and over again.
