### ISSUE TITLE
Request: Show Wins somewhere

### ISSUE THREAD

**Issue by fatzech** [ThatRickGuy/PGSwiss#93]
Not sure if this request is elsewhere but in douhyou you were able to see how many wins each person had at a glance on the screen or via printout. I would like to request that this be added to the screen or the printouts. Or maybe Highlight the winners of each match for the round?

The reason for this would be to make sure we input the matches correctly. I accidentally chose the wrong person in the first round to win one of the matches and we didn't catch it until the third round which caused a lot of headaches. 

Plus it would be nice to glance at it once in a while for my own edification.

**Comment by fatzech** [comment]
I found a way around it by going back one round and setting it to final round. but I would still like to see it listed next to their names.... Maybe with the other info like CP and APD?

**Comment by ThatRickGuy** [comment]
Wins/CP/APD are displayed on the Round screen. Wins have been added to the Pairing screen in version 1.12.1. If you restart the app, it should pull down the latest version.
