### ISSUE TITLE
(Enhancement) Scenario drop down

### ISSUE THREAD

**Issue by Deathnglory** [ThatRickGuy/PGSwiss#95]
Fantastic application - can't wait for the android version.

In several metas locally (Southern Europe) the scenario is table specific not round specific and so different scenarios are played by players each round.  Can you either;
- make the scenario drop down optional and so it is not necessary to populate it to move on in the event?
or
- add the option 'table specific' at the bottom which signifies this.  Organiser will still use this great piece of software and simply add the scenario to each pairing later in the write-up

**Comment by ThatRickGuy** [comment]
Added game specific scenario drop down on the game reporting screen. Each game can have it's own scenario.
